"""initial commit: create all db models including user

Revision ID: 289c2e196e30
Revises: 
Create Date: 2024-12-05 12:13:29.940445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289c2e196e30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('metro_st', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('APARTMENT', 'LAND', 'COMMERCIAL', name='category'), nullable=False),
    sa.Column('action_type', sa.Enum('RENT', 'SALE', name='actiontype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('house_type', sa.Enum('NEW_BUILDING', 'SECONDARY', name='housetype'), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('square_area', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('bathroom', sa.Enum('SEPERATED', 'COMBINED', 'MANY', name='bathroomtype'), nullable=False),
    sa.Column('furnished', sa.Boolean(), nullable=False),
    sa.Column('house_condition', sa.Enum('EURO', 'NORMAL', 'REPAIR', name='housecondition'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.Column('agent_percent', sa.Integer(), nullable=True),
    sa.Column('agent_commission', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_id')
    )
    op.create_index(op.f('ix_apartment_id'), 'apartment', ['id'], unique=False)
    op.create_table('commercial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('APARTMENT', 'LAND', 'COMMERCIAL', name='category'), nullable=False),
    sa.Column('action_type', sa.Enum('RENT', 'SALE', name='actiontype'), nullable=False),
    sa.Column('description', sa.String(length=6000), nullable=True),
    sa.Column('comment', sa.String(length=6000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('square_area', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('BUSINESS_CENTER', 'ADMINISTRATIVE_BUILDING', 'RESIDENTIAL_BUILDING', 'COTTAGE', 'SHOPPING_MALL', 'INDUSTRIAL_ZONE', 'MARKET', 'DETACHED_BUILDING', name='locationcommercial'), nullable=False),
    sa.Column('furnished', sa.Boolean(), nullable=False),
    sa.Column('house_condition', sa.Enum('EURO', 'NORMAL', 'REPAIR', name='housecondition'), nullable=False),
    sa.Column('parking_place', sa.Boolean(), nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.Column('agent_percent', sa.Integer(), nullable=True),
    sa.Column('agent_commission', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_id')
    )
    op.create_index(op.f('ix_commercial_id'), 'commercial', ['id'], unique=False)
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_district_id'), 'district', ['id'], unique=False)
    op.create_table('land',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('APARTMENT', 'LAND', 'COMMERCIAL', name='category'), nullable=False),
    sa.Column('action_type', sa.Enum('RENT', 'SALE', name='actiontype'), nullable=False),
    sa.Column('description', sa.String(length=6000), nullable=True),
    sa.Column('comment', sa.String(length=6000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('square_area', sa.Integer(), nullable=False),
    sa.Column('live_square_area', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('CITY', 'SUBURB', 'COUNTRYSIDE', 'ALONG_ROAD', 'NEAR_POND', 'FOOTHILLS', 'COTTAGE_AREA', 'CLOSED_AREA', name='locationland'), nullable=False),
    sa.Column('furnished', sa.Boolean(), nullable=False),
    sa.Column('house_condition', sa.Enum('EURO', 'NORMAL', 'REPAIR', name='housecondition'), nullable=False),
    sa.Column('parking_place', sa.Boolean(), nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.Column('agent_percent', sa.Integer(), nullable=True),
    sa.Column('agent_commission', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_id')
    )
    op.create_index(op.f('ix_land_id'), 'land', ['id'], unique=False)
    op.create_table('login_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('login_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_info_id'), 'login_info', ['id'], unique=False)
    op.create_table('metro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_metro_id'), 'metro', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('apartment_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_media_id'), 'apartment_media', ['id'], unique=False)
    op.create_table('commercial_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['commercial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_media_id'), 'commercial_media', ['id'], unique=False)
    op.create_table('land_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('land_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['land_id'], ['land.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_media_id'), 'land_media', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_media_id'), table_name='land_media')
    op.drop_table('land_media')
    op.drop_index(op.f('ix_commercial_media_id'), table_name='commercial_media')
    op.drop_table('commercial_media')
    op.drop_index(op.f('ix_apartment_media_id'), table_name='apartment_media')
    op.drop_table('apartment_media')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_metro_id'), table_name='metro')
    op.drop_table('metro')
    op.drop_index(op.f('ix_login_info_id'), table_name='login_info')
    op.drop_table('login_info')
    op.drop_index(op.f('ix_land_id'), table_name='land')
    op.drop_table('land')
    op.drop_index(op.f('ix_district_id'), table_name='district')
    op.drop_table('district')
    op.drop_index(op.f('ix_commercial_id'), table_name='commercial')
    op.drop_table('commercial')
    op.drop_index(op.f('ix_apartment_id'), table_name='apartment')
    op.drop_table('apartment')
    # ### end Alembic commands ###
