"""add four field for each object

Revision ID: 3bec95a02e54
Revises: cf1777eb9ef2
Create Date: 2024-12-20 11:48:08.272600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bec95a02e54'
down_revision: Union[str, None] = 'cf1777eb9ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('status_date', sa.String(length=10), nullable=True))
    op.add_column('apartment', sa.Column('second_responsible', sa.String(), nullable=True))
    op.add_column('apartment', sa.Column('second_agent_percent', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('second_agent_commission', sa.Float(), nullable=True))
    op.add_column('commercial', sa.Column('status_date', sa.String(length=10), nullable=True))
    op.add_column('commercial', sa.Column('second_responsible', sa.String(), nullable=True))
    op.add_column('commercial', sa.Column('second_agent_percent', sa.Integer(), nullable=True))
    op.add_column('commercial', sa.Column('second_agent_commission', sa.Float(), nullable=True))
    op.add_column('land', sa.Column('status_date', sa.String(length=10), nullable=True))
    op.add_column('land', sa.Column('second_responsible', sa.String(), nullable=True))
    op.add_column('land', sa.Column('second_agent_percent', sa.Integer(), nullable=True))
    op.add_column('land', sa.Column('second_agent_commission', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'second_agent_commission')
    op.drop_column('land', 'second_agent_percent')
    op.drop_column('land', 'second_responsible')
    op.drop_column('land', 'status_date')
    op.drop_column('commercial', 'second_agent_commission')
    op.drop_column('commercial', 'second_agent_percent')
    op.drop_column('commercial', 'second_responsible')
    op.drop_column('commercial', 'status_date')
    op.drop_column('apartment', 'second_agent_commission')
    op.drop_column('apartment', 'second_agent_percent')
    op.drop_column('apartment', 'second_responsible')
    op.drop_column('apartment', 'status_date')
    # ### end Alembic commands ###
