"""delete field deal from objects

Revision ID: 3d795b316649
Revises: 485171ee54c1
Create Date: 2024-12-25 21:00:55.104477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d795b316649'
down_revision: Union[str, None] = '485171ee54c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'deal')
    op.drop_column('commercial', 'deal')
    op.drop_column('land', 'deal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('deal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('commercial', sa.Column('deal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('apartment', sa.Column('deal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
