"""add column agency_commission to deal model

Revision ID: 41dcd41a78fa
Revises: 634711138f3b
Create Date: 2025-01-28 16:43:25.790334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dcd41a78fa'
down_revision: Union[str, None] = '634711138f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('agency_commission', sa.Float(), nullable=True))
    op.alter_column('deal', 'commission',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'commission',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('deal', 'agency_commission')
    # ### end Alembic commands ###
