"""create models changelog and operationtype

Revision ID: 501de094bc7d
Revises: 9e5a1ad5164d
Create Date: 2024-12-10 15:30:22.894971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501de094bc7d'
down_revision: Union[str, None] = '9e5a1ad5164d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
