"""make big changes on client model

Revision ID: 5099d919ab4b
Revises: 3d795b316649
Create Date: 2024-12-25 23:07:58.277867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5099d919ab4b'
down_revision: Union[str, None] = '3d795b316649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_id', table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', postgresql.ENUM('RENT', 'SALE', name='actiontype'), autoincrement=False, nullable=False),
    sa.Column('responsible', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hot_clients', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cold_clients', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='client_pkey')
    )
    op.create_index('ix_client_id', 'client', ['id'], unique=False)
    # ### end Alembic commands ###
