"""change a bit view model

Revision ID: 593b6bb50c9c
Revises: 7ea6f2b37210
Create Date: 2024-12-26 01:42:51.023294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593b6bb50c9c'
down_revision: Union[str, None] = '7ea6f2b37210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('view', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('view', 'time',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('view', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('view', 'commission',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('view', 'status_deal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('view', 'status_deal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('view', 'commission',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('view', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('view', 'time',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('view', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
