"""3_add agent_commission field to land model

Revision ID: 6b056f886763
Revises: 4f65ccb72a98
Create Date: 2024-12-04 09:34:57.448197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b056f886763'
down_revision: Union[str, None] = '4f65ccb72a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('agent_commission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'agent_commission')
    # ### end Alembic commands ###
