"""add deal field to all objects

Revision ID: 6c96a9d3c2d9
Revises: 3bec95a02e54
Create Date: 2024-12-21 23:28:15.411172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c96a9d3c2d9'
down_revision: Union[str, None] = '3bec95a02e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('deal', sa.Boolean(), nullable=True))
    op.add_column('commercial', sa.Column('deal', sa.Boolean(), nullable=True))
    op.add_column('land', sa.Column('deal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'deal')
    op.drop_column('commercial', 'deal')
    op.drop_column('apartment', 'deal')
    # ### end Alembic commands ###
