"""change totally view model

Revision ID: 7ea6f2b37210
Revises: 9dbb470cc3d8
Create Date: 2024-12-26 01:39:14.687979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea6f2b37210'
down_revision: Union[str, None] = '9dbb470cc3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('time', sa.String(length=5), nullable=True))
    op.add_column('view', sa.Column('district', sa.String(), nullable=True))
    op.add_column('view', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('view', sa.Column('commission', sa.Integer(), nullable=True))
    op.add_column('view', sa.Column('status_deal', sa.Boolean(), nullable=True))
    op.add_column('view', sa.Column('client_number', sa.String(length=13), nullable=True))
    op.add_column('view', sa.Column('owner_number', sa.String(length=13), nullable=True))
    op.alter_column('view', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('view', 'object_sum')
    op.drop_column('view', 'commission_sum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('commission_sum', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('view', sa.Column('object_sum', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('view', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('view', 'owner_number')
    op.drop_column('view', 'client_number')
    op.drop_column('view', 'status_deal')
    op.drop_column('view', 'commission')
    op.drop_column('view', 'price')
    op.drop_column('view', 'district')
    op.drop_column('view', 'time')
    # ### end Alembic commands ###
