"""recreate client model

Revision ID: 9dbb470cc3d8
Revises: 5099d919ab4b
Create Date: 2024-12-25 23:11:54.359662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '9dbb470cc3d8'
down_revision: Union[str, None] = '5099d919ab4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

action_type_enum = ENUM('RENT', 'SALE', name='actiontype', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    action_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', action_type_enum, nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('district', sa.JSON(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('client_status', sa.Enum('HOT', 'COLD', name='clientstatus'), nullable=True),
    sa.Column('deal_status', sa.Enum('INITIAL_CONTACT', 'NEGOTIATION', 'DECISION_MAKING', 'AGREEMENT_CONTACT', 'DEAL', name='dealstatus'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
