"""create view and client db models

Revision ID: a1969037143f
Revises: 6c96a9d3c2d9
Create Date: 2024-12-22 22:32:05.549941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = 'a1969037143f'
down_revision: Union[str, None] = '6c96a9d3c2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

action_type_enum = ENUM('RENT', 'SALE', name='actiontype', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    action_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', action_type_enum, nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hot_clients', sa.Integer(), nullable=False),
    sa.Column('cold_clients', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', action_type_enum, nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('object_sum', sa.Integer(), nullable=False),
    sa.Column('commission_sum', sa.Integer(), nullable=False),
    sa.Column('agent_percent', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_id'), 'view', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_id'), table_name='view')
    op.drop_table('view')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
