"""change user_id to user and delete relationship

Revision ID: cf1777eb9ef2
Revises: 501de094bc7d
Create Date: 2024-12-11 16:35:14.867688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1777eb9ef2'
down_revision: Union[str, None] = '501de094bc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_log', sa.Column('user', sa.String(), nullable=True))
    op.drop_constraint('change_log_user_id_fkey', 'change_log', type_='foreignkey')
    op.drop_column('change_log', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_log', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('change_log_user_id_fkey', 'change_log', 'user', ['user_id'], ['id'])
    op.drop_column('change_log', 'user')
    # ### end Alembic commands ###
