"""create deal db model

Revision ID: f2e02a2aef80
Revises: a1969037143f
Create Date: 2024-12-23 10:23:55.858700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'f2e02a2aef80'
down_revision: Union[str, None] = 'a1969037143f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

action_type_enum = ENUM('RENT', 'SALE', name='actiontype', create_type=False)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    action_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', action_type_enum, nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('crm_id', sa.String(), nullable=False),
    sa.Column('object_price', sa.Integer(), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.Column('agent_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_id'), 'deal', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_id'), table_name='deal')
    op.drop_table('deal')
    # ### end Alembic commands ###
